# Generated by Django 2.2.2 on 2019-06-25 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=55, unique=True)),
                ('blogHomepage', models.CharField(max_length=60)),
                ('office', models.CharField(max_length=30)),
                ('officeExtention', models.CharField(max_length=30)),
                ('mobile', models.IntegerField(validators=[django.core.validators.MaxValueValidator(11)])),
                ('home', models.CharField(max_length=60)),
                ('address1', models.CharField(max_length=160)),
                ('address2', models.CharField(max_length=160)),
                ('city', models.CharField(max_length=60)),
                ('postCode', models.IntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('state', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('middleName', models.CharField(max_length=30)),
                ('relationship', models.CharField(max_length=30)),
                ('mobilePhone', models.IntegerField(validators=[django.core.validators.MaxValueValidator(11)])),
                ('housePhone', models.IntegerField(validators=[django.core.validators.MaxValueValidator(11)])),
                ('officePhone', models.IntegerField(validators=[django.core.validators.MaxValueValidator(11)])),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employeeId', models.IntegerField(primary_key=True, serialize=False)),
                ('employeementId', models.IntegerField()),
                ('employeeFirstName', models.CharField(max_length=255)),
                ('employeeMiddelName', models.CharField(blank=True, max_length=255, null=True)),
                ('employeeLastName', models.CharField(max_length=255)),
                ('employeeGender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1)),
                ('employeeBirthDate', models.DateField()),
                ('employeeNationality', models.CharField(choices=[('India', 'India')], default='India', max_length=1)),
                ('employeeNationalId', models.IntegerField()),
                ('employeePassport', models.IntegerField(blank=True, null=True)),
                ('employeeEthnicity', models.CharField(blank=True, choices=[('Gernal', 'Gernal'), ('NA', 'NA')], default='NA', max_length=1, null=True)),
                ('employeeReligion', models.CharField(blank=True, choices=[('Gernal', 'Gernal'), ('NA', 'NA')], default='NA', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateJoined', models.DateField()),
                ('endofProbation', models.DateField(null=True)),
                ('position', models.CharField(max_length=30)),
                ('jobStatusEffectiveDate', models.DateField()),
                ('lineManager', models.CharField(max_length=30, null=True)),
                ('department', models.CharField(max_length=30, null=True)),
                ('branch', models.CharField(max_length=30, null=True)),
                ('level', models.CharField(max_length=30, null=True)),
                ('jobType', models.CharField(max_length=30, null=True)),
                ('employmentStatusEffectiveDate', models.DateField()),
                ('jobStatus', models.CharField(max_length=30, null=True)),
                ('leaveWorkflow', models.CharField(max_length=30, null=True)),
                ('workdays', models.CharField(max_length=30, null=True)),
                ('holidays', models.CharField(max_length=30, null=True)),
                ('termStart', models.CharField(max_length=30, null=True)),
                ('termEnd', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
