# Generated by Django 2.2.2 on 2019-06-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employeeId', models.IntegerField(primary_key=True, serialize=False)),
                ('employeementId', models.IntegerField()),
                ('employeeFirstName', models.CharField(max_length=255)),
                ('employeeMiddelName', models.CharField(max_length=255)),
                ('employeeLastName', models.CharField(max_length=255)),
                ('employeeGender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='O', max_length=1)),
                ('employeeBirthDate', models.DateField()),
                ('employeeNationality', models.CharField(choices=[('India', 'India')], default='india', max_length=1)),
                ('employeeNationalId', models.IntegerField()),
                ('employeePassport', models.IntegerField()),
                ('employeeEthnicity', models.CharField(max_length=255)),
                ('employeeReligion', models.CharField(max_length=255)),
            ],
        ),
    ]
