# Generated by Django 2.2.2 on 2019-07-12 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bloodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodgroup', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=30)),
                ('countryCode', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('isactive', 'isactive'), ('notactive', 'inactive')], default='inactive', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employeeId', models.AutoField(primary_key=True, serialize=False)),
                ('employeementId', models.IntegerField(unique=True)),
                ('employeeFirstName', models.CharField(max_length=255)),
                ('employeeMiddelName', models.CharField(blank=True, max_length=255, null=True)),
                ('employeeLastName', models.CharField(max_length=255)),
                ('employeeGender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=15)),
                ('employeeBirthDate', models.DateField()),
                ('employeeNationality', models.CharField(default='India', max_length=15)),
                ('employeeNationalId', models.IntegerField()),
                ('employeePassport', models.CharField(blank=True, max_length=12, null=True)),
                ('employeeEthnicity', models.CharField(blank=True, default='NA', max_length=15, null=True)),
                ('employeeReligion', models.CharField(blank=True, default='NA', max_length=15, null=True)),
                ('employeePhoto', models.ImageField(blank=True, upload_to='photo')),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending')], default='Pending', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ethnicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicityName', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(blank=True, choices=[('isactive', 'isactive'), ('notactive', 'inactive')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='holiDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holidays', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='jobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobStatus', models.CharField(default='intern', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='jobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobType', models.CharField(default='temporary', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='leaveWorkFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveworkflow', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joblevel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='lineManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineManager', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='maritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maritalstatus', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalityName', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('isactive', 'isactive'), ('notactive', 'inactive')], default='notactive', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='numberOfChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfchild', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religionName', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('isactive', 'isactive'), ('notactive', 'inactive')], default='notactive', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='workDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workdays', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateJoined', models.DateField()),
                ('endofProbation', models.DateField(null=True)),
                ('position', models.CharField(max_length=30)),
                ('jobStatusEffectiveDate', models.DateField()),
                ('lineManager', models.CharField(blank=True, max_length=30, null=True)),
                ('department', models.CharField(blank=True, max_length=30, null=True)),
                ('branch', models.CharField(blank=True, max_length=30, null=True)),
                ('level', models.CharField(blank=True, max_length=30, null=True)),
                ('jobType', models.CharField(blank=True, max_length=30, null=True)),
                ('employmentStatusEffectiveDate', models.DateField(blank=True)),
                ('jobStatus', models.CharField(blank=True, max_length=30, null=True)),
                ('leaveWorkflow', models.CharField(blank=True, max_length=30, null=True)),
                ('workdays', models.CharField(blank=True, max_length=30, null=True)),
                ('holidays', models.CharField(blank=True, max_length=30, null=True)),
                ('termStart', models.CharField(max_length=30, null=True)),
                ('termEnd', models.CharField(max_length=30, null=True)),
                ('employeeForeignId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employeeDetails.employee')),
            ],
        ),
        migrations.CreateModel(
            name='employeeHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeHealthHeight', models.CharField(blank=True, max_length=255, null=True)),
                ('employeeHealthWeight', models.CharField(blank=True, max_length=255, null=True)),
                ('employeeHealthBloodGroup', models.CharField(blank=True, default="Don't No", max_length=5, null=True)),
                ('employeeForeignId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employeeDetails.employee')),
            ],
        ),
        migrations.CreateModel(
            name='employeeFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeFamilyMaritalStatus', models.CharField(default='Unmarried', max_length=15)),
                ('employeeFamilyNumberOfChild', models.CharField(default='0', max_length=15, null=True)),
                ('employeeFamilySpouseWorking', models.CharField(default='No', max_length=15, null=True)),
                ('employeeFamilySpouseFirstName', models.CharField(blank=True, max_length=255, null=True)),
                ('employeeFamilySpouseMiddelName', models.CharField(blank=True, max_length=255, null=True)),
                ('employeeFamilySpouseLastName', models.CharField(blank=True, max_length=255, null=True)),
                ('employeeFamilySpouseBirthDate', models.DateField(blank=True, null=True)),
                ('employeeFamilySpouseNationality', models.CharField(default='India', max_length=15)),
                ('employeeFamilySpouseNationalId', models.CharField(blank=True, max_length=8, null=True)),
                ('employeeFamilySpousePassport', models.CharField(blank=True, max_length=12, null=True)),
                ('employeeFamilySpouseEthnicity', models.CharField(blank=True, default='NA', max_length=15, null=True)),
                ('employeeFamilySpouseReligion', models.CharField(blank=True, default='NA', max_length=15, null=True)),
                ('employeeForeignId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employeeDetails.employee')),
            ],
        ),
        migrations.CreateModel(
            name='employeeChildren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeChildrenFirstName', models.CharField(blank=True, max_length=255, null=True)),
                ('employeeChildrenMiddelName', models.CharField(blank=True, max_length=255, null=True)),
                ('employeeChildrenLastName', models.CharField(blank=True, max_length=255, null=True)),
                ('employeeChildrenBirthDate', models.DateField(blank=True, null=True)),
                ('employeeChildrenGender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=15, null=True)),
                ('employeeChildrenMaritalStatus', models.CharField(default='Unmarried', max_length=1)),
                ('employeeForeignId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employeeDetails.employee')),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20)),
                ('branchObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeDetails.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=55, null=True)),
                ('blogHomepage', models.CharField(max_length=60, null=True)),
                ('office', models.CharField(max_length=30, null=True)),
                ('officeExtention', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('home', models.CharField(max_length=60, null=True)),
                ('address1', models.CharField(max_length=160, null=True)),
                ('address2', models.CharField(max_length=160, null=True)),
                ('city', models.CharField(max_length=60, null=True)),
                ('postCode', models.CharField(blank=True, max_length=12, null=True)),
                ('state', models.CharField(max_length=80, null=True)),
                ('country', models.CharField(max_length=80)),
                ('firstName', models.CharField(max_length=30, null=True)),
                ('lastName', models.CharField(max_length=30, null=True)),
                ('middleName', models.CharField(max_length=30, null=True)),
                ('relationship', models.CharField(max_length=30, null=True)),
                ('mobilePhone', models.CharField(blank=True, max_length=12, null=True)),
                ('housePhone', models.CharField(blank=True, max_length=12, null=True)),
                ('officePhone', models.CharField(blank=True, max_length=12, null=True)),
                ('employeeForeignId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employeeDetails.employee')),
            ],
        ),
    ]
