# Generated by Django 2.2.2 on 2019-06-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeEthnicity',
            field=models.CharField(blank=True, choices=[('Gernal', 'Gernal'), ('NA', 'NA')], default='NA', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeGender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeMiddelName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeNationality',
            field=models.CharField(choices=[('India', 'India')], default='India', max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeePassport',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeReligion',
            field=models.CharField(blank=True, choices=[('Gernal', 'Gernal'), ('NA', 'NA')], default='NA', max_length=1, null=True),
        ),
    ]
