# Generated by Django 2.2.2 on 2019-06-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0002_auto_20190624_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
