# Generated by Django 2.2.2 on 2019-07-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0002_auto_20190718_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeechildren',
            name='employeeChildrenMaritalStatus',
            field=models.CharField(default='Unmarried', max_length=15),
        ),
    ]
