# Generated by Django 2.2.2 on 2019-06-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0003_auto_20190624_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeementId',
            field=models.CharField(max_length=255),
        ),
    ]
