# Generated by Django 2.2.2 on 2019-06-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0004_auto_20190624_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employeePhoto',
            field=models.ImageField(blank=True, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeNationalId',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeNationality',
            field=models.CharField(choices=[('India', 'India'), ('Canada', 'Canada')], default='India', max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeementId',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
