# Generated by Django 2.2.2 on 2019-06-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0005_auto_20190624_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeeHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeHealthHeight', models.CharField(blank=True, max_length=255, null=True)),
                ('employeeHealthWeight', models.CharField(blank=True, max_length=255, null=True)),
                ('employeeHealthBloodGroup', models.CharField(blank=True, choices=[('AN', 'AN'), ('AP', 'AP'), ('B', 'B'), ('BP', 'BP'), ('ABN', 'ABN'), ('ABP', 'ABP'), ('OP', 'OP'), ('ON', 'ON'), ("Don/'t No", "Don/'t No")], default="Don't No", max_length=1, null=True)),
                ('employeeForeignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeDetails.employee', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='employeeFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeFamilyMaritalStatus', models.CharField(choices=[('Married', 'Married'), ('UnMarried', 'Unmarried')], default='Unmarried', max_length=1)),
                ('employeeFamilyNumberOfChild', models.CharField(default='0', max_length=5)),
                ('employeeFamilySpouseWorking', models.CharField(default='No', max_length=5)),
                ('employeeFamilySpouseFirstName', models.CharField(blank=True, max_length=255, null=True)),
                ('employeeFamilySpouseMiddelName', models.CharField(blank=True, max_length=255, null=True)),
                ('employeeFamilySpouseLastName', models.CharField(blank=True, max_length=255, null=True)),
                ('employeeFamilySpouseBirthDate', models.DateField(blank=True, null=True)),
                ('employeeFamilySpouseNationality', models.CharField(choices=[('India', 'India'), ('Canada', 'Canada')], default='India', max_length=1)),
                ('employeeFamilySpouseNationalId', models.IntegerField(blank=True, null=True)),
                ('employeeFamilySpousePassport', models.IntegerField(blank=True, null=True)),
                ('employeeFamilySpouseEthnicity', models.CharField(blank=True, choices=[('Gernal', 'Gernal'), ('NA', 'NA')], default='NA', max_length=1, null=True)),
                ('employeeFamilySpouseReligion', models.CharField(blank=True, choices=[('Gernal', 'Gernal'), ('NA', 'NA')], default='NA', max_length=1, null=True)),
                ('employeeForeignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeDetails.employee', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='employeeChildren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeChildrenFirstName', models.CharField(blank=True, max_length=255, null=True)),
                ('employeeChildrenMiddelName', models.CharField(blank=True, max_length=255, null=True)),
                ('employeeChildrenLastName', models.CharField(blank=True, max_length=255, null=True)),
                ('employeeChildrenBirthDate', models.DateField(blank=True, null=True)),
                ('employeeChildrenGender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1)),
                ('employeeChildrenMaritalStatus', models.CharField(choices=[('Married', 'Married'), ('UnMarried', 'Unmarried')], default='Unmarried', max_length=1)),
                ('employeeForeignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeDetails.employee')),
            ],
        ),
    ]
