# Generated by Django 2.2.2 on 2019-06-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0007_auto_20190625_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefamily',
            name='employeeFamilySpouseNationalId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeefamily',
            name='employeeFamilySpousePassport',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeefamily',
            name='employeeFamilySpouseWorking',
            field=models.CharField(default='No', max_length=5, null=True),
        ),
    ]
