# Generated by Django 2.2.2 on 2019-06-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0008_auto_20190625_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehealth',
            name='employeeHealthBloodGroup',
            field=models.CharField(blank=True, choices=[('AN', 'AN'), ('AP', 'AP'), ('B', 'B'), ('BP', 'BP'), ('ABN', 'ABN'), ('ABP', 'ABP'), ('OP', 'OP'), ('ON', 'ON'), ("Don/'t know", "Don/'t know")], default="Don't No", max_length=1, null=True),
        ),
    ]
