# Generated by Django 2.2.2 on 2019-06-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0010_auto_20190625_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeEthnicity',
            field=models.CharField(blank=True, choices=[('Gernal', 'Gernal'), ('NA', 'NA')], default='NA', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeGender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeNationality',
            field=models.CharField(choices=[('India', 'India'), ('Canada', 'Canada')], default='India', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeReligion',
            field=models.CharField(blank=True, choices=[('Gernal', 'Gernal'), ('NA', 'NA')], default='NA', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employeechildren',
            name='employeeChildrenGender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employeefamily',
            name='employeeFamilyMaritalStatus',
            field=models.CharField(choices=[('Married', 'Married'), ('UnMarried', 'Unmarried')], default='Unmarried', max_length=15),
        ),
        migrations.AlterField(
            model_name='employeefamily',
            name='employeeFamilyNumberOfChild',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='employeefamily',
            name='employeeFamilySpouseEthnicity',
            field=models.CharField(blank=True, choices=[('Gernal', 'Gernal'), ('NA', 'NA')], default='NA', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employeefamily',
            name='employeeFamilySpouseNationality',
            field=models.CharField(choices=[('India', 'India'), ('Canada', 'Canada')], default='India', max_length=15),
        ),
        migrations.AlterField(
            model_name='employeefamily',
            name='employeeFamilySpouseReligion',
            field=models.CharField(blank=True, choices=[('Gernal', 'Gernal'), ('NA', 'NA')], default='NA', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employeefamily',
            name='employeeFamilySpouseWorking',
            field=models.CharField(default='No', max_length=15, null=True),
        ),
    ]
