# Generated by Django 2.2.2 on 2019-06-28 08:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0011_auto_20190625_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehealth',
            name='employeeHealthBloodGroup',
            field=models.CharField(blank=True, choices=[('AN', 'AN'), ('AP', 'AP'), ('B', 'B'), ('BP', 'BP'), ('ABN', 'ABN'), ('ABP', 'ABP'), ('OP', 'OP'), ('ON', 'ON'), ("Don/'t know", "Don/'t know")], default="Don't No", max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateJoined', models.DateField()),
                ('endofProbation', models.DateField(null=True)),
                ('position', models.CharField(max_length=30)),
                ('jobStatusEffectiveDate', models.DateField()),
                ('lineManager', models.CharField(max_length=30, null=True)),
                ('department', models.CharField(max_length=30, null=True)),
                ('branch', models.CharField(max_length=30, null=True)),
                ('level', models.CharField(max_length=30, null=True)),
                ('jobType', models.CharField(max_length=30, null=True)),
                ('employmentStatusEffectiveDate', models.DateField()),
                ('jobStatus', models.CharField(max_length=30, null=True)),
                ('leaveWorkflow', models.CharField(max_length=30, null=True)),
                ('workdays', models.CharField(max_length=30, null=True)),
                ('holidays', models.CharField(max_length=30, null=True)),
                ('termStart', models.CharField(max_length=30, null=True)),
                ('termEnd', models.CharField(max_length=30, null=True)),
                ('employeeForeignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeDetails.employee', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=55, unique=True)),
                ('blogHomepage', models.CharField(max_length=60)),
                ('office', models.CharField(max_length=30, null=True)),
                ('officeExtention', models.CharField(max_length=30)),
                ('mobile', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(11)])),
                ('home', models.CharField(max_length=60, null=True)),
                ('address1', models.CharField(max_length=160)),
                ('address2', models.CharField(max_length=160)),
                ('city', models.CharField(max_length=60)),
                ('postCode', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(20)])),
                ('state', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('middleName', models.CharField(max_length=30)),
                ('relationship', models.CharField(max_length=30)),
                ('mobilePhone', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(11)])),
                ('housePhone', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(11)])),
                ('officePhone', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(11)])),
                ('employeeForeignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeDetails.employee', unique=True)),
            ],
        ),
    ]
