# Generated by Django 2.2.2 on 2019-06-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0012_auto_20190628_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='leaveWorkflow',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
