# Generated by Django 2.2.2 on 2019-06-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0014_auto_20190629_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address1',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address2',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='blogHomepage',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='firstName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lastName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='middleName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='officeExtention',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='relationship',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
