# Generated by Django 2.2.2 on 2019-06-30 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0016_auto_20190629_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='housePhone',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobilePhone',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='officePhone',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='postCode',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
