# Generated by Django 2.2.2 on 2019-06-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0018_auto_20190701_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='branch',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='employmentStatusEffectiveDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='holidays',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobStatus',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobType',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='leaveWorkflow',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='lineManager',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='workdays',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
