# Generated by Django 2.2.2 on 2019-07-02 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0020_auto_20190702_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=30)),
                ('countryCode', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('isactive', 'isactive'), ('notactive', 'notactive')], default='notactive', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ethnicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicityName', models.CharField(max_length=30)),
                ('status', models.CharField(blank=True, choices=[('isactive', 'isactive'), ('notactive', 'notactive')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='holiDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holidays', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='jobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobStatus', models.CharField(choices=[('intern', 'intern'), ('permanent', 'permanent')], default='intern', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='jobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobType', models.CharField(choices=[('permanent', 'permanent'), ('temporary', 'temporary')], default='temporary', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='leaveWorkFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveworkflow', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joblevel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='lineManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineManagerList', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalityName', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('isactive', 'isactive'), ('notactive', 'notactive')], default='notactive', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religionName', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('isactive', 'isactive'), ('notactive', 'notactive')], default='notactive', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='workDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workdays', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20)),
                ('branchObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeDetails.branch')),
            ],
        ),
    ]
