# Generated by Django 2.2.2 on 2019-07-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0021_auto_20190703_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefamily',
            name='employeeFamilySpouseBirthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
