# Generated by Django 2.2.2 on 2019-07-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0022_auto_20190705_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefamily',
            name='employeeFamilySpouseNationalId',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='employeefamily',
            name='employeeFamilySpousePassport',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
