# Generated by Django 2.2.2 on 2019-07-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0023_auto_20190706_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='officeExtention',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
