# Generated by Django 2.2.2 on 2019-07-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0028_auto_20190706_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending')], default='Pending', max_length=30),
        ),
    ]
