# Generated by Django 2.2.2 on 2019-07-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0029_auto_20190706_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefamily',
            name='employeeFamilySpouseNationality',
            field=models.CharField(default='India', max_length=15),
        ),
    ]
