# Generated by Django 2.2.2 on 2019-07-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0031_auto_20190708_1326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='numberOfChild',
        ),
    ]
