# Generated by Django 2.2.2 on 2019-07-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0033_numberofchild'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeechildren',
            name='employeeChildKey',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='country',
            name='status',
            field=models.CharField(choices=[('isactive', 'isactive'), ('notactive', 'inactive')], default='inactive', max_length=30),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='status',
            field=models.CharField(blank=True, choices=[('isactive', 'isactive'), ('notactive', 'inactive')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='status',
            field=models.CharField(choices=[('isactive', 'isactive'), ('notactive', 'inactive')], default='notactive', max_length=30),
        ),
        migrations.AlterField(
            model_name='religion',
            name='status',
            field=models.CharField(choices=[('isactive', 'isactive'), ('notactive', 'inactive')], default='notactive', max_length=30),
        ),
    ]
