# Generated by Django 2.2.2 on 2019-07-09 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0034_auto_20190709_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeechildren',
            name='employeeChildKey',
        ),
    ]
