# Generated by Django 2.2.2 on 2019-07-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0035_remove_employeechildren_employeechildkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeePassport',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
