# Generated by Django 2.2.2 on 2019-07-12 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDetails', '0036_auto_20190710_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='employeeForeignId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employeeDetails.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeementId',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employeefamily',
            name='employeeForeignId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employeeDetails.employee'),
        ),
        migrations.AlterField(
            model_name='employeehealth',
            name='employeeForeignId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employeeDetails.employee'),
        ),
        migrations.AlterField(
            model_name='job',
            name='employeeForeignId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employeeDetails.employee'),
        ),
    ]
